### ISSUE TITLE
Fatal Error:

### ISSUE THREAD

**Issue by SerafimArts** [phpvisualdebt/phpvisualdebt#5]
Version 1.0.3
PHP 7.1

```
PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Stmt\Trait_::isFinal() in ~/vendor/phpvisualdebt/phpvisualdebt/src/Questioner/FinalKeywordQuestioner.php:28
Stack trace:
#0 ~/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(159): PHPVisualDebt\Questioner\FinalKeywordQuestioner->enterNode(Object(PhpParser\Node\Stmt\Trait_))
#1 ~/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(101): PhpParser\NodeTraverser->traverseArray(Array)
#2 ~/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(171): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Namespace_))
#3 ~/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(85): PhpParser\NodeTraverser->traverseArray(Array)
#4 ~/vendor/phpvisualdebt/phpvisualdebt/src/StaticAnalyzer.php(57): PhpParser\NodeTraverser->traverse(Array)
#5 /home in ~/vendor/phpvisualdebt/phpvisualdebt/src/Questioner/FinalKeywordQuestioner.php on line 28
```

**Comment by brzuchal** [comment]
@SerafimArts Please provide a sample code so the issue can be repeated.

**Comment by SerafimArts** [comment]
Hmmm,
1) Open console
2) Exec `composer require phpvisualdebt/phpvisualdebt`
3) Exec `php ~/vendor/bin/phpvisualdebt` into any dir (Everything where I checked throwing this error).

**Comment by MetalArend** [comment]
Same here, using `composer global require --dev phpvisualdebt/phpvisualdebt`.

**Comment by faustbrian** [comment]
Same issue, global and local installation.
